version: '3.7'
services:
  wordpress:
    image: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: database-docker-project.ckgdhkqntfx2.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin321
      WORDPRESS_DB_NAME: databaseDockerProject
    volumes:
      - /mnt/efs/wordpress:/var/www/html
